spring:
  datasource:
    url: jdbc:h2:mem:idusdb;MODE=MySQL
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org.springframework.web: debug
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace